config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: "home#index"

  resources :users, only: [:index, :show, :edit, :update] do
    resources :recipes
      resources :reviews, only: [:new, :create, :index, :show]
  end

  resources :recipes do
    resources :reviews, only: [:new, :create, :show]
  end

  resources :ingredients

  get 'quickest' => 'recipes#quickest'

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients
  has_many :reviews
  has_many :ingredients, through: :recipe_ingredients
  belongs_to :user, :class_name => 'User', :foreign_key => 'user_id', optional: true
  validates :name, :prep_time, :cook_time, :instructions, presence: true
  validates :prep_time, :cook_time, numericality: { only_integer: true }
  ##validates :ingredients, presence: true

  scope :quickest, -> { where('cook_time + prep_time < ?', 21) }

  def recipe_ingredients_attributes=(params)
    if self.save
    params.each do |k, recipe_ingredient|
        if !recipe_ingredient[:ingredient_id].empty?
          RecipeIngredient.create(quantity: recipe_ingredient[:quantity], ingredient_id: recipe_ingredient[:ingredient_id], recipe_id: self.id)
        elsif recipe_ingredient[:ingredient][:name].present?
          @ingredient = Ingredient.create(name: recipe_ingredient[:ingredient][:name])
          @recipe_ingredients = RecipeIngredient.create(quantity: recipe_ingredient[:quantity], recipe_id: self.id, ingredient_id: @ingredient.id)
        end
      end
    end
  end

  def delete_ingredients_from_recipe
      ingredients.size.times do
      ingredient = RecipeIngredient.find_by(recipe_id: self.id)
      ingredient.delete
    end
  end

  def add_ingredients_to_recipe(params)
      delete_ingredients_from_recipe
      params[:recipe_ingredients_attributes].each do |k, recipe_ingredient|

      if recipe_ingredient[:ingredient][:name].present?
        ingredient_name = recipe_ingredient[:ingredient][:name].downcase
        ingredient = Ingredient.find_or_create_by(name: ingredient_name)
      elsif recipe_ingredient[:ingredient_id].present?
        ingredient = Ingredient.find_by(id: recipe_ingredient[:ingredient_id])
      end

      if recipe_ingredient[:quantity].present?
        RecipeIngredient.create(quantity: recipe_ingredient[:quantity], ingredient_id: ingredient.id, recipe_id: self.id )
      end
    end
  end

  def total_time
    cook_time + prep_time
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
    @user = current_user
    @recipe = Recipe.new
    5.times do
      @recipe_ingredient = @recipe.recipe_ingredients.build
      @recipe_ingredient.build_ingredient
    end
  end

  def create
    @recipe = Recipe.new(recipe_params) do |r|
      r.user = current_user
    end
    if @recipe.save
      @recipe.add_ingredients_to_recipe(recipe_ingredient_params)
      respond_to do |format|
        format.html { redirect_to recipes_path }
        format.js { } #controller method sends back response as js
      end
    else
      render 'new'
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @review = Review.new
  end

  def edit
    @recipe = Recipe.find(params[:id])
    if @recipe.ingredients.length === 1
      4.times do
        @recipe_ingredient = @recipe.recipe_ingredients.build
        @recipe_ingredient.build_ingredient
      end
    elsif @recipe.ingredients.length === 2
      3.times do
        @recipe_ingredient = @recipe.recipe_ingredients.build
        @recipe_ingredient.build_ingredient
      end
    elsif @recipe.ingredients.length === 3
      2.times do
        @recipe_ingredient = @recipe.recipe_ingredients.build
        @recipe_ingredient.build_ingredient
      end
    elsif @recipe.ingredients.length === 4
      1.time do
        @recipe_ingredient = @recipe.recipe_ingredients.build
        @recipe_ingredient.build_ingredient
      end
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      @recipe.add_ingredients_to_recipe(recipe_ingredient_params)
      flash[:notice] = 'Recipe was successfully updated.'
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end

  def quickest
    @recipes = Recipe.quickest
  end

  private
  def recipe_params
    params.require(:recipe).permit(:name, :prep_time, :cook_time, :instructions, :user_id, recipe_ingredients_attributes: [:quantity, :ingredient_id, ingredient: [:name]])
  end

  def recipe_ingredient_params
    params.require(:recipe).permit(recipe_ingredients_attributes: [:quantity, :ingredient_id, ingredient: [:name]])
  end

end

app/views/recipes/_form.html.erb
<div class="field_with_errors">
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@recipe.errors.count, "error") %>
        prohibited this recipe from being saved:
      </h2>

      <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for @recipe, html: {id: :recipe_form} do |f| %>
  <%= f.text_field :name, placeholder: "Recipe Name" %>
  <%= f.text_field :prep_time, placeholder: "Prep Time (min.)" %>
  <%= f.text_field :cook_time, placeholder: "Cook Time (min.)" %>

  <h3>Ingredients:</h3>
  <div class="ingredients">
    <%= f.fields_for :recipe_ingredients do |ri| %>
    <div>
      <%= ri.fields_for :ingredient, @recipe.ingredients.build do |ingredient| %>
      <%= ingredient.text_field :name, placeholder: "Name" %>
    <% end %>
    Or
    <%= ri.collection_select :ingredient_id, Ingredient.order('name ASC').all, :id, :name_for_select, include_blank: 'Select Ingredient' %>
    <%= ri.text_field :quantity, placeholder: "Quantity" %>
  </div>
<% end %>

<h3>Instructions:</h3>
<%= f.text_area :instructions %>
</div>

<%= f.submit %>
<% end %>
</div>
<hr>

app/views/recipes/_recipe.html.erb
<li>
  <%= link_to recipe.name, recipe_path(recipe) %> |
  <% if recipe.reviews.present? %>
  Difficulty: <%= recipe.reviews.average(:difficulty).round %> |
  Reviews: <%= recipe.reviews.count %>
  <% else %>
      No Reviews
  <% end %>
  <br>
  <%= link_to "Delete", recipe_path(recipe), method: 'delete' %>
  <%= link_to "Edit", edit_recipe_path(recipe) %>
</li>

app/views/recipes/create.js.erb
$('#recipes').append("<%= j render partial: 'recipe', locals: {recipe: @recipe} %>");

app/views/recipes/edit.html.erb
<section>
  <h3>Edit Recipe</h3>
  <div class="field_with_errors">
    <% if @recipe.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@recipe.errors.count, "error") %>
          prohibited this recipe from being saved:
        </h2>

        <ul>
          <% @recipe.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_for @recipe, html: {id: :recipe_edit_form} do |f| %>
    <%= f.text_field :name, placeholder: "Recipe Name" %>
    <%= f.text_field :prep_time, placeholder: "Prep Time (min.)" %>
    <%= f.text_field :cook_time, placeholder: "Cook Time (min.)" %>

    <h3>Ingredients:</h3>
    <div class="ingredients">
      <%= f.fields_for :recipe_ingredients do |ri| %>
      <div>
        <%= ri.fields_for :ingredient, @recipe.ingredients.build do |ingredient| %>
        <%= ingredient.text_field :name, placeholder: "Name" %>
      <% end %>
      Or
      <%= ri.collection_select :ingredient_id, Ingredient.order('name ASC').all, :id, :name_for_select, include_blank: 'Select Ingredient' %>
      <%= ri.text_field :quantity, placeholder: "Quantity" %>
    </div>
  <% end %>

  <h3>Instructions:</h3>
  <%= f.text_area :instructions %>
  </div>

  <%= f.submit %>
  <% end %>
  </div>
  <hr>
    <%= link_to 'Go Back', recipe_path %>
</section>

app/views/recipes/index.html.erb
<section>
  <header>
    <h2>Recipes</h2>
  </header>

  <ul id="recipes">
    <%= render @recipes %>
  </ul>

  <br>

  <button onclick="timeSavers()" class="btn">Time Saving Recipes</button>
  <div id="quick" style="display:none;"></div>
</section>

<section>
  <h2>Add Recipe</h2>
<%= render 'form' %>
</section>

app/views/recipes/quickest.html.erb
<!-- <section id="quickest"> <header> <h2>Time Saving Recipes</h2> </header> -->
<div id="quick">
  <table id="recipes">
    <tr>
      <th>Recipe Name</th>
      <th>Total Time</th>
    </tr>
    <tr>
      <% @recipes.each do |r| %>
        <td><%= link_to r.name, recipe_path(r) %></td>
        <td><%= r.total_time %>
          min.</td>
      </tr>
    <% end %>
  </table>
</div>
<!-- </section> -->

app/views/recipes/show.html.erb
<section class="recipes">
  <h3><%= @recipe.name %></h3>
  <p>Prep Time:
    <%= @recipe.prep_time %>
    minutes
  </p>
  <p>Cook Time:
    <%= @recipe.cook_time %>
    minutes
  </p>
  <%= render 'ingredients/list_ingredients', recipe: @recipe %>
  <h3>Instructions:</h3>
  <%= @recipe.instructions %>
  <br>
  <%= link_to 'Edit Recipe', edit_user_recipe_path(@recipe) %>
  |
  <%= link_to 'Remove Recipe', @recipe, :method => :delete %>
  |
  <%= link_to 'Go Back', recipes_path %><br><br>
  <%= render 'reviews/form', review: @recipe.reviews.new, recipe: @recipe %>
</section>

<section id="reviews-section">
  <button onclick="renderReviews('submitted-reviews')">See Reviews</button>
  <div id="submitted-reviews" style="display:none;">
    <% @recipe.reviews.each do |r| %>
      <div class="review-body">
        <% if r.description != nil %>
          <li>Description:
            <%= r.description %><br>
          <% end %>
          <% if r.difficulty != nil && r.reviewer != nil %>
            Difficulty:
            <%= r.difficulty %><br>
            Name:
            <%= r.reviewer %>
          </li>
        <% end %>
      <% end %>
    </div>
  </div>
</section>