config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: "home#index"

  resources :users, only: [:index, :show, :edit, :update] do
    resources :recipes
      resources :reviews, only: [:new, :create, :index, :show]
  end

  resources :recipes do
    resources :reviews, only: [:new, :create, :show]
  end

  resources :ingredients

  get 'quickest' => 'recipes#quickest'

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
  validates :name, :presence => true

  def name_for_select
    name.downcase
  end

  def self.search(term)
    if term
      where('name LIKE ?', "%#{term}%")
    else
      order('name ASC')
    end
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.search(params[:term])
    @ingredient = Ingredient.new
    respond_to do |format|
      format.html {render :index}
      format.json { render json: @ingredients }
      # GET /ingredients.json
    end
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      render json: @ingredient, status: 201
    else
      flash[:error] = "Error. Ingredient not added."
      render 'new'
    end
  end

  def show
    @ingredient = Ingredient.find(params[:id])
    respond_to do |format|
      format.html {render :show}
      format.json { render json: @ingredient }
      # GET /ingredients/1.json
    end
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
  end

  private
  def ingredient_params
    params.require(:ingredient).permit(:name, :quantity, :recipe_id, :term)
  end
end

app/views/ingredients/_list_ingredients.html.erb
<h3>Ingredients:</h3>
  <% @recipe.recipe_ingredients.each do |i| %>
    <p class="recipeIngredients"><%= i.quantity %> - <%= i.ingredient.name if i.ingredient %></p>
  <% end %>
<br>

app/views/ingredients/index.html.erb
<section>
  <h3>Ingredients:</h3>
  <hr>
  <div id="ingredient_list">
    <%= form_tag(ingredients_path, method: :get) do %>
      <%= text_field_tag :term, params[:term] %>
      <%= submit_tag 'Search Ingredients', name: nil %>
    <% end %>
    OR
    <%= form_for @ingredient, html: {class: :new_ingredient} do |f| %>
    <%= f.text_field :name, placeholder: "Ingredient Name" %>
    <%= f.submit 'Add New Ingredient '%>
    <% end %>
    <hr>
    <% @ingredients.each do |i| %>
      <ul>

        <li><button class="ing" data-id="<%=i.id%>"><%= i.name %></button></li>
      </ul>
    <% end %>
  </div>
  <button id="reverse" class="btn">Reverse</button>
  <div class="reversed"></div>
<div class="ingredient-recipes"></div>
</section>

app/views/ingredients/show.html.erb
<section class="recipes">
  <% if @ingredient.recipes.empty? %>
    <h4>No recipes with <%= @ingredient.name%></h4>
  <% else %>
    <h4>Recipes with
      <%= @ingredient.name %>:</h4>
    <% @ingredient.recipes.each do |r| %>
      <li><%= link_to r.name, recipe_path(r) %></li>
    <% end %>
  <% end %>
  <hr>
  <%= link_to 'Go Back', ingredients_path %> Or <%= link_to 'Add New Recipe', recipes_path %>

</section>